### ISSUE TITLE
Max Listners

### ISSUE THREAD

**Issue by snowbreeze** [sandeepmistry/noble-device#19]
Any ideas on this?

```
[Fri Apr 01 2016 11:25:25] [ERROR] (node) warning: possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit.
[Fri Apr 01 2016 11:25:25] [ERROR] Trace
    at Peripheral.addListener (events.js:179:15)
    at NobleDevice (/home/pi/prophecy-gateway/src/node_modules/sensortag/node_modules/noble-device/lib/noble-device.js:18:20)
    at Noble.constructor.onDiscover (/home/pi/prophecy-gateway/src/node_modules/sensortag/node_modules/noble-device/lib/util.js:28:22)
    at Noble.emit (events.js:129:20)
    at Noble.onDiscover (/home/pi/prophecy-gateway/src/node_modules/noble/lib/noble.js:152:10)
    at emit (events.js:118:17)
    at NobleBindings.onDiscover (/home/pi/prophecy-gateway/src/node_modules/noble/lib/hci-socket/bindings.js:160:10)
    at emit (events.js:118:17)
    at Gap.onHciLeAdvertisingReport (/home/pi/prophecy-gateway/src/node_modules/noble/lib/hci-socket/gap.js:160:10)

```

**Comment by wooks123kr** [comment]
You must call removeAllListener when device is disconnected.

**Comment by snowbreeze** [comment]
This is happening at startup. When i try adding a new device this comes.

**Comment by sandeepmistry** [comment]
@snowbreeze please provide a minimal code sample that reproduces the issue.

**Comment by sandeepmistry** [comment]
Closing due to lack of activity.
